---
# This playbook installs VIM and its plugins

- name: Install vim package
  dnf: name=vim state=latest

- name: Clone Ultimate vimrc repo
  git: >
    repo=https://github.com/amix/vimrc.git
    accept_hostkey=yes
    force=yes
    dest={{ user.home }}/.vim_runtime
  become: yes
  become_user: "{{ user.name }}"

- name: Add favorite plugins
  git: >
    dest={{ user.home }}/.vim_runtime/{{ item.dest }}
    force=yes
    repo={{ item.repo }}
  with_items:
    - { repo: "http://github.com/sjl/gundo.vim.git", dest: "sources_non_forked/gundo" }
#    - { repo: "http://github.com/kakkyz81/evervim.git ", dest: "sources_non_forked/evervim" }
#    - { repo: "http://github.com/fholgado/minibufexpl.vim.git ", dest: "sources_non_forked/minibuxeplorer" }
    - { repo: "http://github.com/powerline/powerline.git", dest: "sources_non_forked/powerline" }
    - { repo: "https://github.com/dermusikman/sonicpi.vim", dest: "sources_non_forked/sonicpi" }
    - { repo: "https://github.com/tpope/vim-rails.git", dest: "sources_non_forked/rails" }
    - { repo: "https://github.com/tpope/vim-bundler.git", dest: "sources_non_forked/bundler" }
    - { repo: "https://github.com/tpope/vim-dispatch.git", dest: "sources_non_forked/dispatch" }

  become: yes
  become_user: "{{ user.name }}"

- name: Run Ultimate vimrc installer
  shell: sh {{ user.home }}/.vim_runtime/install_awesome_vimrc.sh
  become: yes
  become_user: "{{ user.name }}"

- name: Fix permissions
  file: >
    path={{ user.home }}/.vim_runtime
    owner={{ user.uid }}
    group={{ user.gid }}
    recurse=yes

# if become_user doesn't work;
# https://stackoverflow.com/a/24808173
