---
- name: Install OpenVPN  package
  package: name={{ item }} state=latest
  notify: openvpn restart
  with_items:
      - "{{ openvpn_package_name }}"

- name: Enable IP Forward
  sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes

- name: Copy universal templates
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode={{ item.mode }}
  notify: openvpn restart
  with_items:
      - { src: 'etc_openvpn_server.conf.j2', dest: '/etc/openvpn/server.conf', mode: '0600' }

# - include: redhat_firewall.yml
#   when: ansible_os_family == "RedHat"

# - include: debian_firewall.yml
#   when: ansible_os_family == "Debian"

- name: Enable OpenVPN service
  service: name=openvpn@server.service enabled=yes
  when: ansible_os_family == "RedHat"
