---
ssl_certs_country: "US"
ssl_certs_locality: "Chicago"
ssl_certs_organization: "some org"
ssl_certs_state: "Illinois"
ssl_certs_common_name: "someorg.net"
ssl_certs_days: "3650"
ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"

ssl_certs_path: "/etc/ssl/certs/{{ssl_certs_common_name}}"
ssl_certs_path_owner: "root"
ssl_certs_path_group: "root"
ssl_certs_privkey_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.key"
ssl_certs_cert_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.crt"
ssl_certs_csr_path: "{{ssl_certs_path}}/{{ssl_certs_common_name}}.csr"
ssl_certs_dhparam_path: "{{ssl_certs_path}}/dhparam.pem"
ssl_certs_mode: 0644

ssl_certs_local_privkey_path: "/etc/pki/ssl/{{ssl_certs_common_name}}.key"
ssl_certs_local_cert_path: "/etc/pki/ssl/{{ssl_certs_common_name}}.crt"

ssl_certs_generate_self_signed: false
ssl_certs_key_size: "2048"
ssl_certs_generate_dh_param: false
ssl_certs_dhparam_size: "2048"
