---

- name: Install RVM
  include: 'rvm.yml'
  become: yes
  become_user: '{{ rvm1_user }}'

- name: Install Ruby and Gems
  include: 'rubies.yml'
  become: yes
  become_user: '{{ rvm1_user }}'

- name: switch to global gemset and install a few gems
  command: bash -lc "rvm gemset use global && gem install pry pry-doc bundler rubocop"
  when: "'--user-install' in rvm1_install_flags"
  become: yes
  become_user: '{{ rvm1_user }}'
