---

- name: start sshd
  service: name=sshd state=started enabled=yes

- name: copy over login banner
  template: >
    src=issue.j2
    dest=/etc/issue
    backup=yes
    owner=0 group=0 mode=0644

- name: configure sshd
  template: >
    src=sshd_config.j2
    dest={{ sshd_config_basedir }}/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
    validate='/usr/sbin/sshd -T -f %s'
  notify: restart sshd
