---

- name: copy gitlfs source to temp folder
  copy: >
    src=git-lfs-linux-amd64-2.2.1.tar.gz
    dest='{{ temp_dir }}/git-lfs-linux-amd64-2.2.1.tar.gz'
  
- name: extract the source archive into the source folder
  unarchive: >
    src='{{ temp_dir }}/git-lfs-linux-amd64-2.2.1.tar.gz'
    dest='{{ local_src_dir }}/'
    owner='{{ user.uid }}'
    group='{{ user.gid }}'

- name: run the installer
  command: ./install.sh
  args:
    chdir: '{{ local_src_dir }}/git-lfs-2.2.1'
