---

- name: install fedora workstation repos
  dnf: >
    name='fedora-workstation-repositories'
    state=present
  tags: ['repos']

- name: install rpmfusion nonfree repo
  dnf: >
    name='http://download1.rpmfusion.org/nonfree/fedora/releases/28/Everything/x86_64/os/Packages/r/rpmfusion-nonfree-release-28-1.noarch.rpm'
    state=present
  tags: ['rpmfusion']

- name: install rpmfusion free repo
  dnf: >
    name='http://download1.rpmfusion.org/free/fedora/releases/28/Everything/x86_64/os/Packages/r/rpmfusion-free-release-28-1.noarch.rpm'
    state=present
  tags: ['rpmfusion']

- name: enable some copr repos
  command: 'dnf -y copr enable {{ item }}'
  with_items:
    - "tcg/themes"
    - "ycollet/linuxmao"
    - "oleastre/abcMIDI"
    - "seeitcoming/rcm"
    - "yaroslav/i3desktop"
    - "yelanxin/deadbeef"
    - "heliocastro/hack-fonts"
    - "rabiny/albert"
  tags: ['repos', 'copr']
