---

#- name: install libraries for plugins
#  pip: name={{ item }} extra_args='--user' state=present
#  with_items:
#    - pyenchant
#    - pygtkspellcheck
#    - seqdiag
#  become: yes
#  become_user: '{{ user.name }}'

- name: install pygtksourceview
  dnf: name={{ item }} state=present
  with_items:
    - Zim
    - pygtksourceview
