---

- name: install jack audio packages
  dnf: name={{ item }} state=present
  with_items:
    - jack-audio-connection-kit
    - jack-audio-connection-kit-example-clients
    - jack-audio-connection-kit-dbus
    - jack-keyboard
    - jack-rack
    - jack_capture
    - pulseaudio-module-jack
  tags: ['jack-audio']
