---

- include: alsa.yml
  tags: ['alsa']

- include: jack.yml
  tags: ['jack']

- include: sonicpi.yml
  tags: ['sonic']

- include: patchage.yml
  tags: ['audio']

- include: utils.yml
  tags: ['audio_tools']

#- include: rosegarden.yml
#  tags: ['rosegarden']

- #include: zita.yml
  #tags: ['zita']

#- include: linuxsampler.yml
#  tags: ['linuxsampler']

- include: effects.yml
  tags: ['effects']

- include: score.yml
  tags: ['abc']

- include: synth.yml
  tags: ['synth']

- include: deadbeef.yml
  tags: ['deadbeef']

- include: realtime.yml
  tags: ['realtime']

- name: install these things
  dnf: name={{ item }} state=present
  with_items:
    - guitarix
    - hydrogen
    - non-sequencer
    - qmidiarp
    - qsynth
    - rakarrack
    - sooperlooper
    - vmpk
    - zynaddsubfx
    - lv2-swh-plugins
    - python3-rdflib
    - mixxx
  tags: ['core']
