---

- name: install dependencies for compton
  dnf: name={{ item }} state=present
  with_items:
    - libX11-devel
    - libXcomposite-devel
    - libXdamage-devel
    - libXrender-devel
    - libXrandr-devel
    - libXinerama-devel
    - libconfig-devel
    - dbus-devel
    - libdrm-devel
    - mesa-libGL-devel
    - asciidoc

- name: clone compton
  git: >
    repo=https://github.com/chjj/compton.git
    dest="{{ local_src_dir }}/compton"
    accept_hostkey=yes
    update=no
    force=no
  become: yes
  become_user: "{{ user.name }}"

- name: run make on compton
  command: make
  args:
    chdir: "{{ local_src_dir }}/compton"
  become: yes
  become_user: "{{ user.name }}"

- name: run make install on compton
  command: make install
  args:
    chdir: "{{ local_src_dir }}/compton"
